# fly.toml app configuration file generated for zentra-announcement-bar on 2026-02-19T12:44:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zentra-announcement-bar'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Add health check configuration
  [[http_service.checks]]
    grace_period = "60s"
    interval = "15s"
    timeout = "10s"
    method = "GET"
    path = "/"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
