# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e07e85dc659ac38270e3a8c381d2e87b"
name = "Zentra Announcement Bar"
application_url = "https://zentra-announcement-bar.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes"

[auth]
redirect_urls = [
  "https://zentra-announcement-bar.fly.dev/auth/callback",
  "https://zentra-announcement-bar.fly.dev/auth/shopify/callback",
  "https://zentra-announcement-bar.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"




